### ISSUE TITLE
【提问】请问如何修改【推荐】首页的工具顺序

### ISSUE THREAD

**Issue by Shunamxiao** [liuyueyi/quick-tools#3]
### 相关截图
![image](https://github.com/liuyueyi/quick-tools/assets/92215296/6ce5bb1f-8b85-4828-a96d-ad56a150703d)

**Comment by liuyueyi** [comment]
![image](https://github.com/liuyueyi/quick-tools/assets/5125892/3a4d9217-61ae-475d-bf3a-ffb65d7355f6)

调整 tools.js 中的 recommend 为 true的表示放在推荐这个tab页；hot可以用支持排序

**Comment by Shunamxiao** [comment]
欧克，感谢分享哈，如果前后端分离的话感觉这个项目会比较方便哈哈哈

**Comment by Shunamxiao** [comment]
> ![image](https://private-user-images.githubusercontent.com/5125892/292698585-3a4d9217-61ae-475d-bf3a-ffb65d7355f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MTQzMjMsIm5iZiI6MTcwMzUxNDAyMywicGF0aCI6Ii81MTI1ODkyLzI5MjY5ODU4NS0zYTRkOTIxNy02MWFlLTQ3NWQtYmYzYS1mZmI2NWQ3MzU1ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMTQyMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2E4ODM2OGNiZDZhMWFhZDg1N2VkY2UyMTc4ZDE5ZjBiOTkwNWE0NjQzNWRkNzFkMGViYjZlZjg4MzNjNzRkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5Ll1RZ7m5sC0cy0n3tixjFaaQgi14Fq7BPaHmqDNVw0)
> 
> 调整 tools.js 中的 recommend 为 true的表示放在推荐这个tab页；hot可以用支持排序

![image](https://github.com/liuyueyi/quick-tools/assets/92215296/52392c6d-af02-418b-95f6-ce2762b18903)
再问下，这个icon图标用的是哪家的啊

**Comment by liuyueyi** [comment]
![image](https://github.com/liuyueyi/quick-tools/assets/5125892/14e62902-b55c-41c8-8b35-0195a9a460a9)
iconfont.js 文件中定义的
